name: Build and Release

on:
  push:
    tags:
      - 'v*' # Activa este Action solo cuando haces un push de un tag que empiece por v (ej: v1.0.1)

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write # Necesario para crear Releases en GitHub

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build and Package Electron App
        run: npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Proporcionado automáticamente por GitHub

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            build-dist/*.exe
            build-dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
